openapi: 3.1.0
info:
  title: Portfolio Tools Hub API
  version: 1.0.0
  description: API for Portfolio Tools Hub
servers:
  - url: https://api.example.com/v1
    description: 本番環境
  - url: https://localhost:3000/v1
    description: 開発環境

paths:
  /:
    $ref: './definitions/paths/sample/root.yaml'
  /users:
    $ref: './definitions/paths/user/users.yaml'

components:
  schemas:
    RootMessage:
      allOf:
        - $ref: './definitions/schemas/sample/root.yaml#/Message'
    User:
      allOf:
        - $ref: './definitions/schemas/user/users.yaml#/User'
  
  responses:
    BadRequest:
      $ref: './responses.yaml#/BadRequest'
    Unauthorized:
      $ref: './responses.yaml#/Unauthorized'
    Forbidden:
      $ref: './responses.yaml#/Forbidden'
    NotFound:
      $ref: './responses.yaml#/NotFound'
    InternalServerError:
      $ref: './responses.yaml#/InternalServerError'

tags:
  - name: general
    description: 一般的なエンドポイント
  - name: user
    description: ユーザー関連のエンドポイント