openapi: 3.1.0
info:
  title: Portfolio Tools Hub API
  version: 1.0.0
  description: API for Portfolio Tools Hub
servers:
  - url: https://api.example.com/v1
    description: 本番環境
  - url: https://localhost:3000/v1
    description: 開発環境

paths:
  /:
    $ref: './paths/general/checkRoot.yaml'
  /signUp:
    $ref: './paths/auth/signUp.yaml'
  /userIdList:
    $ref: './paths/users/getUserIdList.yaml'
  /userNameList:
    $ref: './paths/users/getUserNameList.yaml'

components:
  schemas:
    rootMessageResponse:
      allOf:
        - $ref: './schemas/general/checkRoot.yaml#/checkRootResponse'
    signUp:
      allOf:
        - $ref: './schemas/auth/signUp.yaml#/signUpResponse'
    userIdList:
      allOf:
        - $ref: './schemas/users/getUserIdList.yaml#/getUserIdListResponse'
    userNameList:
      allOf:
        - $ref: './schemas/users/getUserNameList.yaml#/getUserNameListResponse'
  
  parameters:
    checkRootRequest:
      $ref: './schemas/general/checkRoot.yaml#/checkRootRequest'
    signUpRequest:
      $ref: './schemas/auth/signUp.yaml#/signUpRequest'
    getUserIdListRequest:
      $ref: './schemas/users/getUserIdList.yaml#/getUserIdListRequest'
    getUserNameListRequest:
      $ref: './schemas/users/getUserNameList.yaml#/getUserNameListRequest'
  
  responses:
    BadRequest:
      $ref: './responses.yaml#/BadRequest'
    Unauthorized:
      $ref: './responses.yaml#/Unauthorized'
    Forbidden:
      $ref: './responses.yaml#/Forbidden'
    NotFound:
      $ref: './responses.yaml#/NotFound'
    InternalServerError:
      $ref: './responses.yaml#/InternalServerError'

tags:
  - name: general
    description: 一般的なエンドポイント
  - name: auth
    description: 認証関連のエンドポイント
  - name: users
    description: ユーザー関連のエンドポイント