openapi: 3.0.3
info:
  title: Portfolio Tools Hub API
  version: 1.0.0
  description: API for Portfolio Tools Hub
servers:
  - url: https://api.example.com
    description: 本番環境
  - url: https://localhost:3000
    description: 開発環境

paths:
  /:
    $ref: './paths/general/checkRoot.yaml'
  /auth/signup:
    $ref: './paths/auth/signUp.yaml'
  /auth/login:
    $ref: './paths/auth/login.yaml'
  /auth/logout:
    $ref: './paths/auth/logout.yaml'
  /auth/refresh:
    $ref: './paths/auth/refreshToken.yaml'
  /auth/resetPassword:
    $ref: './paths/auth/resetPassword.yaml'
  /auth/oauth/github:
    $ref: './paths/auth/oauth/github.yaml'
  /auth/oauth/google:
    $ref: './paths/auth/oauth/google.yaml'
  /userIdList:
    $ref: './paths/users/getUserIdList.yaml'
  /userNameList:
    $ref: './paths/users/getUserNameList.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabaseが提供するJWTトークンを使用した認証
  
  responses:
    # 400番
    BadRequest:
      description: リクエストの形式が不正です
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: エラーメッセージ
              details:
                type: array
                description: バリデーションエラーの詳細
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      description: エラーのあるフィールド名
                    message:
                      type: string
                      description: 具体的なエラー内容
            required:
              - error
    # 401番
    Unauthorized:
      description: 認証が必要です
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: エラーメッセージ
                example: "認証が必要です"
            required:
              - error
    # 403番
    Forbidden:
      description: このリソースにアクセスする権限がありません
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: エラーメッセージ
                example: "アクセス権限がありません"
            required:
              - error
    # 404番
    NotFound:
      description: リクエストされたリソースが見つかりません
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: エラーメッセージ
                example: "リソースが見つかりません"
            required:
              - error
    # 500番
    InternalServerError:
      description: サーバー内部でエラーが発生しました
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: エラーメッセージ
                example: "内部サーバーエラーが発生しました"
            required:
              - error

tags:
  - name: general
    description: 一般的なエンドポイント
  - name: auth
    description: 認証関連のエンドポイント
  - name: users
    description: ユーザー関連のエンドポイント